# Generated by Django 4.0.2 on 2022-03-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_first_model_human'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='First_model',
            new_name='FirstModel',
        ),
        migrations.RenameField(
            model_name='firstmodel',
            old_name='human',
            new_name='humanrace',
        ),
    ]
